### ISSUE TITLE
MMM-SL doesn't update

### ISSUE THREAD

**Issue by clabbo** [teppos/MMM-SL#7] opened 2018-07-29 21:24 UTC
Hi
Since the latest upgrade I struggle to get the MMM-SL module to update. The notification schedule seems to work:
				notification_schedule: [
					{ notification: "DECREMENT_SL", schedule: "0-59 0-23 * * *", },
					{ notification: "UPDATE_SL", schedule: '*/10 * * * *', },
				],

The log is full of these events - an UPDATE_SL every 10 minutes and DECREMENT_SL every minute:

MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:50:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to **UPDATE_SL**
MMM-ModuleScheduler will next send SEND_NOTIFICATION to UPDATE_SL at Sat Jul 28 2018 09:00:00 GMT+0200 (CEST) based on "*/10 * * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:51:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:52:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:53:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:54:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:55:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:56:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:57:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:58:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 08:59:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to DECREMENT_SL
MMM-ModuleScheduler will next send SEND_NOTIFICATION to DECREMENT_SL at Sat Jul 28 2018 09:00:00 GMT+0200 (CEST) based on "0-59 0-23 * * *"
MMM-ModuleScheduler is sending SEND_NOTIFICATION to **UPDATE_SL**
MMM-ModuleScheduler will next send SEND_NOTIFICATION to UPDATE_SL at Sat Jul 28 2018 09:10:00 GMT+0200 (CEST) based on "*/10 * * * *"

My DNS filter show that calls to api.sl.se are made very scarcely, several hours in between. I can see calls made by other modules more or less every minute so it does not seem to be network related. If I refresh the MagicMirror with the MMM-Remote-Control or even by opening the MagicMirror on a computer the SL module is refreshed.

The SL module is great, do you think it is possible to bring it back to its former glory?
/Claes

**Comment by teppos** [comment] 2018-07-30 20:11
Hmm.. that sounds weird. I'll look into it in the near future if/what I broke with the last few updates.

**Comment by teppos** [comment] 2018-08-07 09:31
This should be fixed now. Caused by a change in default values.

**Closed by teppos** 2018-08-07 09:31 UTC
